"""sync_design_icons の単体テスト。"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "sync_design_icons.py"


def _load_mod():
    spec = importlib.util.spec_from_file_location("sync_design_icons", SCRIPT)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    sys.modules["sync_design_icons"] = mod
    spec.loader.exec_module(mod)
    return mod


def test_collect_icon_names_sorted_unique() -> None:
    mod = _load_mod()
    catalog = [
        {"icons": ["Plus", "Settings"]},
        {"icons": ["Image", "Images"]},
    ]
    assert mod.collect_icon_names(catalog) == [
        "Image",
        "Images",
        "Plus",
        "Settings",
    ]


def test_render_icons_ts_includes_header_and_exports() -> None:
    mod = _load_mod()
    data = {
        "catalog": [{"icons": ["Plus"], "usage_ja": "追加", "note_ja": "x"}],
        "export_types": ["LucideIcon", "LucideProps"],
    }
    out = mod.render_icons_ts(
        data, package="lucide-react", header=mod.ICONS_TS_HEADER
    )
    assert "GENERATED by scripts/sync_design_icons.py" in out
    assert "docs/design/meta/icons.json" in out
    assert "  Plus," in out
    assert 'export type { LucideIcon, LucideProps } from "lucide-react";' in out


def test_render_mobile_icons_uses_native_package() -> None:
    mod = _load_mod()
    data = {"catalog": [{"icons": ["Plus"]}]}
    out = mod.render_icons_ts(
        data, package="lucide-react-native", header=mod.MOBILE_ICONS_TS_HEADER
    )
    assert 'from "lucide-react-native"' in out
    assert "export type" not in out


def test_patch_icons_md_replaces_marker_block() -> None:
    mod = _load_mod()
    content = (
        "## 採用一覧\n\n"
        "<!-- AUTO:icons-catalog START — x -->\n"
        "| old |\n"
        "<!-- AUTO:icons-catalog END -->\n"
    )
    catalog = [{"usage_ja": "設定", "icons": ["Settings"], "note_ja": "ナビ"}]
    patched = mod.patch_icons_md(content, catalog)
    assert "| 設定 | `Settings` | ナビ |" in patched
    assert "| old |" not in patched


def test_icons_json_is_valid_catalog() -> None:
    meta = ROOT / "docs" / "design" / "meta" / "icons.json"
    data = json.loads(meta.read_text(encoding="utf-8"))
    mod = _load_mod()
    names = mod.collect_icon_names(data["catalog"])
    assert "Plus" in names
    assert len(names) >= 10
