/**
 * GENERATED by scripts/sync_lucide_icon_catalog.py — 手編集禁止
 * 正本: docs/design/meta/lucide_icon_picker.json
 */

export const LUCIDE_ICON_FALLBACK_CATEGORY = "tag" as const;
export const LUCIDE_ICON_FALLBACK_STORAGE = "map-pin" as const;

export type LucideIconSlug =
  | "archive"
  | "award"
  | "badge"
  | "bed"
  | "bird"
  | "book-marked"
  | "book-open"
  | "bookmark"
  | "box"
  | "brick-wall"
  | "briefcase"
  | "brush"
  | "camera"
  | "car"
  | "cat"
  | "cherry"
  | "circle"
  | "circle-dot"
  | "cloud"
  | "coffee"
  | "crown"
  | "dice-5"
  | "disc"
  | "ellipsis"
  | "file-text"
  | "fish"
  | "flower-2"
  | "frame"
  | "gallery-vertical"
  | "gamepad-2"
  | "gem"
  | "gift"
  | "glasses"
  | "grid-3x3"
  | "hand-heart"
  | "headphones"
  | "heart"
  | "home"
  | "image"
  | "images"
  | "inbox"
  | "key-round"
  | "lamp"
  | "lamp-desk"
  | "laptop"
  | "layers"
  | "layout-grid"
  | "library"
  | "link"
  | "map-pin"
  | "medal"
  | "mic"
  | "mic-2"
  | "moon"
  | "music"
  | "music-2"
  | "newspaper"
  | "package"
  | "palette"
  | "party-popper"
  | "pen"
  | "pencil"
  | "person-standing"
  | "picture-in-picture"
  | "pin"
  | "plane"
  | "puzzle"
  | "rabbit"
  | "radio"
  | "ribbon"
  | "scissors"
  | "scroll-text"
  | "shirt"
  | "shopping-bag"
  | "smartphone"
  | "smile"
  | "sofa"
  | "sparkles"
  | "square"
  | "star"
  | "sticker"
  | "store"
  | "sun"
  | "tag"
  | "tags"
  | "ticket"
  | "train"
  | "trophy"
  | "tv"
  | "umbrella"
  | "user-round"
  | "video"
  | "wand-2"
  | "warehouse"
  | "watch";

export const LUCIDE_ICON_SLUGS: readonly LucideIconSlug[] = [
  "archive",
  "award",
  "badge",
  "bed",
  "bird",
  "book-marked",
  "book-open",
  "bookmark",
  "box",
  "brick-wall",
  "briefcase",
  "brush",
  "camera",
  "car",
  "cat",
  "cherry",
  "circle",
  "circle-dot",
  "cloud",
  "coffee",
  "crown",
  "dice-5",
  "disc",
  "ellipsis",
  "file-text",
  "fish",
  "flower-2",
  "frame",
  "gallery-vertical",
  "gamepad-2",
  "gem",
  "gift",
  "glasses",
  "grid-3x3",
  "hand-heart",
  "headphones",
  "heart",
  "home",
  "image",
  "images",
  "inbox",
  "key-round",
  "lamp",
  "lamp-desk",
  "laptop",
  "layers",
  "layout-grid",
  "library",
  "link",
  "map-pin",
  "medal",
  "mic",
  "mic-2",
  "moon",
  "music",
  "music-2",
  "newspaper",
  "package",
  "palette",
  "party-popper",
  "pen",
  "pencil",
  "person-standing",
  "picture-in-picture",
  "pin",
  "plane",
  "puzzle",
  "rabbit",
  "radio",
  "ribbon",
  "scissors",
  "scroll-text",
  "shirt",
  "shopping-bag",
  "smartphone",
  "smile",
  "sofa",
  "sparkles",
  "square",
  "star",
  "sticker",
  "store",
  "sun",
  "tag",
  "tags",
  "ticket",
  "train",
  "trophy",
  "tv",
  "umbrella",
  "user-round",
  "video",
  "wand-2",
  "warehouse",
  "watch",
] as const;

export const LUCIDE_ICON_SLUG_SET = new Set<string>(LUCIDE_ICON_SLUGS);

export type LucidePickerOption = { slug: LucideIconSlug; label_ja: string };

export const LUCIDE_CATEGORY_PICKER: readonly LucidePickerOption[] = [
  { slug: "layers", label_ja: "アクリル・板" },
  { slug: "square", label_ja: "スクエア" },
  { slug: "circle", label_ja: "丸・缶バッジ" },
  { slug: "circle-dot", label_ja: "ドット" },
  { slug: "badge", label_ja: "バッジ" },
  { slug: "medal", label_ja: "メダル" },
  { slug: "star", label_ja: "星" },
  { slug: "sparkles", label_ja: "キラリ" },
  { slug: "heart", label_ja: "ハート" },
  { slug: "hand-heart", label_ja: "推し" },
  { slug: "gift", label_ja: "ギフト" },
  { slug: "ribbon", label_ja: "リボン" },
  { slug: "party-popper", label_ja: "お祝い" },
  { slug: "shopping-bag", label_ja: "ショップ袋" },
  { slug: "package", label_ja: "パッケージ" },
  { slug: "box", label_ja: "箱" },
  { slug: "tag", label_ja: "タグ" },
  { slug: "tags", label_ja: "タグ複数" },
  { slug: "ticket", label_ja: "チケット" },
  { slug: "file-text", label_ja: "紙・書類" },
  { slug: "scroll-text", label_ja: "巻物" },
  { slug: "newspaper", label_ja: "新聞・フライヤー" },
  { slug: "book-open", label_ja: "本" },
  { slug: "book-marked", label_ja: "ブックマーク本" },
  { slug: "image", label_ja: "画像" },
  { slug: "images", label_ja: "写真複数" },
  { slug: "camera", label_ja: "カメラ" },
  { slug: "video", label_ja: "動画" },
  { slug: "music", label_ja: "音楽" },
  { slug: "music-2", label_ja: "音符" },
  { slug: "mic", label_ja: "マイク" },
  { slug: "mic-2", label_ja: "ペンライト系" },
  { slug: "headphones", label_ja: "ヘッドホン" },
  { slug: "radio", label_ja: "ラジオ" },
  { slug: "disc", label_ja: "CD" },
  { slug: "person-standing", label_ja: "フィギュア" },
  { slug: "user-round", label_ja: "キャラ" },
  { slug: "smile", label_ja: "スマイル" },
  { slug: "cat", label_ja: "猫" },
  { slug: "rabbit", label_ja: "うさぎ" },
  { slug: "bird", label_ja: "鳥" },
  { slug: "fish", label_ja: "魚" },
  { slug: "shirt", label_ja: "アパレル" },
  { slug: "glasses", label_ja: "メガネ" },
  { slug: "watch", label_ja: "時計" },
  { slug: "palette", label_ja: "アート" },
  { slug: "brush", label_ja: "ブラシ" },
  { slug: "pen", label_ja: "ペン" },
  { slug: "pencil", label_ja: "鉛筆" },
  { slug: "scissors", label_ja: "はさみ" },
  { slug: "sticker", label_ja: "ステッカー" },
  { slug: "frame", label_ja: "額・ポスター" },
  { slug: "picture-in-picture", label_ja: "ピクチャ" },
  { slug: "gallery-vertical", label_ja: "ギャラリー" },
  { slug: "grid-3x3", label_ja: "グリッド" },
  { slug: "layout-grid", label_ja: "レイアウト" },
  { slug: "wand-2", label_ja: "魔法" },
  { slug: "gem", label_ja: "宝石" },
  { slug: "crown", label_ja: "クラウン" },
  { slug: "trophy", label_ja: "トロフィー" },
  { slug: "award", label_ja: "賞" },
  { slug: "gamepad-2", label_ja: "ゲーム" },
  { slug: "puzzle", label_ja: "パズル" },
  { slug: "dice-5", label_ja: "ダイス" },
  { slug: "coffee", label_ja: "カフェ" },
  { slug: "flower-2", label_ja: "お花" },
  { slug: "cherry", label_ja: "チェリー" },
  { slug: "sun", label_ja: "晴れ" },
  { slug: "moon", label_ja: "夜" },
  { slug: "cloud", label_ja: "雲" },
  { slug: "umbrella", label_ja: "傘" },
  { slug: "smartphone", label_ja: "スマホ" },
  { slug: "tv", label_ja: "TV" },
  { slug: "car", label_ja: "車" },
  { slug: "plane", label_ja: "飛行機" },
  { slug: "train", label_ja: "電車" },
  { slug: "pin", label_ja: "ピン" },
  { slug: "link", label_ja: "リンク" },
  { slug: "key-round", label_ja: "キーホルダー" },
  { slug: "bookmark", label_ja: "しおり" },
  { slug: "ellipsis", label_ja: "その他" },
] as const;

export const LUCIDE_STORAGE_PICKER: readonly LucidePickerOption[] = [
  { slug: "archive", label_ja: "タンス・アーカイブ" },
  { slug: "library", label_ja: "本棚・棚" },
  { slug: "box", label_ja: "箱・ケース" },
  { slug: "package", label_ja: "梱包" },
  { slug: "inbox", label_ja: "引き出し" },
  { slug: "warehouse", label_ja: "倉庫" },
  { slug: "home", label_ja: "自宅" },
  { slug: "store", label_ja: "店舗" },
  { slug: "map-pin", label_ja: "場所" },
  { slug: "frame", label_ja: "壁・額" },
  { slug: "gallery-vertical", label_ja: "壁展示" },
  { slug: "lamp-desk", label_ja: "机" },
  { slug: "lamp", label_ja: "ランプ横" },
  { slug: "laptop", label_ja: "PCデスク" },
  { slug: "sofa", label_ja: "ソファ" },
  { slug: "bed", label_ja: "ベッド" },
  { slug: "shirt", label_ja: "クローゼット" },
  { slug: "shopping-bag", label_ja: "袋" },
  { slug: "briefcase", label_ja: "仕事用" },
  { slug: "car", label_ja: "車内" },
  { slug: "train", label_ja: "通勤" },
  { slug: "plane", label_ja: "旅行" },
  { slug: "umbrella", label_ja: "玄関" },
  { slug: "brick-wall", label_ja: "壁面" },
  { slug: "grid-3x3", label_ja: "格子" },
  { slug: "layout-grid", label_ja: "仕切り" },
  { slug: "bookmark", label_ja: "ファイル" },
  { slug: "book-open", label_ja: "バインダー" },
  { slug: "layers", label_ja: "重ね置き" },
  { slug: "ellipsis", label_ja: "その他" },
] as const;

export function slugToPascal(slug: string): string {
  return slug
    .split("-")
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}
