#!/usr/bin/env python3
"""コードから docs/product/generated/* を再生成する（製品 as-built）。

使い方:
  python scripts/generate_product_docs.py

手編集禁止。意図（value / roadmap / flows / acceptance）は触らない。
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
GEN = ROOT / "docs" / "product" / "generated"
META = ROOT / "docs" / "product" / "meta" / "feature_status.json"
WEB_APP = ROOT / "apps" / "web" / "src" / "app"
API_ROUTERS = ROOT / "apps" / "api" / "app" / "routers"
API_SERVICES = ROOT / "apps" / "api" / "app" / "services"
SHARED_INDEX = ROOT / "packages" / "shared" / "src" / "index.ts"

HEADER = (
    "<!-- GENERATED by scripts/generate_product_docs.py — 手編集禁止。"
    " 再生成: python scripts/generate_product_docs.py -->\n"
)

ROUTE_DECORATOR_RE = re.compile(
    r"@(?P<var>\w+)\.(?P<method>get|post|put|patch|delete)\(\s*[\"'](?P<path>[^\"']*)[\"']",
    re.IGNORECASE,
)
API_PATHS_RE = re.compile(
    r"export const API_PATHS = \{(?P<body>.*?)\} as const",
    re.DOTALL,
)
API_PATH_ENTRY_RE = re.compile(
    r"(\w+)\s*:\s*[\"']([^\"']+)[\"']",
)


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def scan_web_routes() -> list[dict[str, str]]:
    if not WEB_APP.is_dir():
        return []
    routes: list[dict[str, str]] = []
    for path in sorted(WEB_APP.rglob("*")):
        if not path.is_file():
            continue
        name = path.name
        if name not in ("page.tsx", "page.ts", "page.jsx", "route.ts", "route.js"):
            continue
        rel = path.relative_to(WEB_APP)
        parts: list[str] = []
        for part in rel.parts[:-1]:
            if part.startswith("(") and part.endswith(")"):
                continue
            # next-intl の [locale] は論理パスから除外（/gallery として記録）
            if part == "[locale]":
                continue
            parts.append(part)
        url = "/" + "/".join(parts) if parts else "/"
        kind = "page" if name.startswith("page.") else "route"
        routes.append(
            {
                "path": url,
                "kind": kind,
                "file": str(path.relative_to(ROOT)).replace("\\", "/"),
            }
        )
    return routes


def join_prefix(prefix: str, path: str) -> str:
    prefix = prefix.rstrip("/")
    if not path:
        return prefix or "/"
    if path.startswith("/"):
        return f"{prefix}{path}" if prefix else path
    return f"{prefix}/{path}" if prefix else f"/{path}"


def scan_api_routes() -> list[dict[str, str]]:
    if not API_ROUTERS.is_dir():
        return []
    found: list[dict[str, str]] = []
    for py in sorted(API_ROUTERS.glob("*.py")):
        if py.name.startswith("_"):
            continue
        text = py.read_text(encoding="utf-8")
        prefixes: dict[str, str] = {}
        for m in re.finditer(
            r"^(\w+)\s*=\s*APIRouter\s*\((?P<args>.*)\)",
            text,
            re.MULTILINE,
        ):
            var = m.group(1)
            args = m.group("args")
            pm = re.search(r"prefix\s*=\s*[\"']([^\"']+)[\"']", args)
            prefixes[var] = pm.group(1) if pm else ""

        for m in ROUTE_DECORATOR_RE.finditer(text):
            var = m.group("var")
            method = m.group("method").upper()
            path = m.group("path")
            prefix = prefixes.get(var, "")
            full = join_prefix(prefix, path)
            found.append(
                {
                    "method": method,
                    "path": full,
                    "file": str(py.relative_to(ROOT)).replace("\\", "/"),
                    "router_var": var,
                }
            )
    found.sort(key=lambda r: (r["path"], r["method"]))
    return found


def scan_shared_paths() -> list[dict[str, str]]:
    if not SHARED_INDEX.is_file():
        return []
    text = SHARED_INDEX.read_text(encoding="utf-8")
    block = API_PATHS_RE.search(text)
    if not block:
        return []
    return [
        {"key": m.group(1), "path": m.group(2)}
        for m in API_PATH_ENTRY_RE.finditer(block.group("body"))
    ]


def scan_services() -> list[dict[str, str]]:
    if not API_SERVICES.is_dir():
        return []
    return [
        {
            "name": py.stem,
            "file": str(py.relative_to(ROOT)).replace("\\", "/"),
        }
        for py in sorted(API_SERVICES.glob("*_service.py"))
    ]


def load_features() -> list[dict[str, Any]]:
    if not META.is_file():
        return []
    data = json.loads(META.read_text(encoding="utf-8"))
    return list(data.get("features") or [])


def path_pattern_to_regex(pattern: str) -> re.Pattern[str]:
    """`/gallery/[id]` や `/products/{registered_product_id}` を実パス照合用へ。"""
    escaped = re.escape(pattern)
    escaped = re.sub(r"\\\[.*?\\\]", r"[^/]+", escaped)
    escaped = re.sub(r"\\\{.*?\\\}", r"[^/]+", escaped)
    return re.compile("^" + escaped + "$")


def path_covered(pattern: str, actual_paths: set[str]) -> bool:
    rx = path_pattern_to_regex(pattern)
    return any(rx.match(p) for p in actual_paths)


def normalize_api_path(path: str) -> str:
    """共有定数と FastAPI パスの照合用（末尾スラッシュ除去）。"""
    if path != "/" and path.endswith("/"):
        return path.rstrip("/")
    return path or "/"


def compute_gaps(
    features: list[dict[str, Any]],
    web_paths: set[str],
    api_paths: set[str],
    shared_paths: set[str],
) -> list[dict[str, str]]:
    """evidence・expected paths・deferred 勝手実装・shared ずれを検査。"""
    gaps: list[dict[str, str]] = []

    for feat in features:
        status = feat.get("status")
        fid = str(feat.get("id") or "?")
        evidence = list(feat.get("evidence_paths") or [])
        expected_web = list(feat.get("expected_web_paths") or [])
        expected_api = list(feat.get("expected_api_paths") or [])

        if status in ("planned", "deferred"):
            if evidence:
                gaps.append(
                    {
                        "id": fid,
                        "kind": "status_has_evidence",
                        "detail": f"{status} だが evidence_paths がある（整理候補）",
                    }
                )
            # deferred/planned なのに expected ルートが as-built に出たら警告
            for p in expected_web:
                if path_covered(p, web_paths):
                    gaps.append(
                        {
                            "id": fid,
                            "kind": "unexpected_web_route",
                            "detail": f"{status} なのに Web `{p}` が実装されている",
                        }
                    )
            for p in expected_api:
                if path_covered(p, api_paths):
                    gaps.append(
                        {
                            "id": fid,
                            "kind": "unexpected_api_route",
                            "detail": f"{status} なのに API `{p}` が実装されている",
                        }
                    )
            continue

        if status in ("shipped", "partial"):
            if not evidence:
                gaps.append(
                    {
                        "id": fid,
                        "kind": "missing_evidence",
                        "detail": f"{status} だが evidence_paths が空",
                    }
                )
            for p in evidence:
                if not (ROOT / p).exists():
                    gaps.append(
                        {
                            "id": fid,
                            "kind": "missing_file",
                            "detail": f"evidence が無い: {p}",
                        }
                    )
            for p in expected_web:
                if not path_covered(p, web_paths):
                    gaps.append(
                        {
                            "id": fid,
                            "kind": "missing_expected_web",
                            "detail": f"{status} だが Web `{p}` が as-built に無い",
                        }
                    )
            for p in expected_api:
                if not path_covered(p, api_paths):
                    gaps.append(
                        {
                            "id": fid,
                            "kind": "missing_expected_api",
                            "detail": f"{status} だが API `{p}` が as-built に無い",
                        }
                    )

    # shared ↔ api のざっくり差分（テンプレ引数は正規化して比較）
    for sp in sorted(shared_paths):
        if not path_covered(sp, api_paths) and not any(
            path_pattern_to_regex(ap).match(normalize_api_path(sp))
            or path_pattern_to_regex(normalize_api_path(sp)).match(ap)
            for ap in api_paths
        ):
            # shared がテンプレ無しのとき、api 側に同じ path があるか
            if normalize_api_path(sp) not in {normalize_api_path(a) for a in api_paths}:
                # 部分一致: /products は /products/{id} の親として許容
                if not any(
                    normalize_api_path(a) == normalize_api_path(sp)
                    or normalize_api_path(a).startswith(normalize_api_path(sp) + "/")
                    for a in api_paths
                ):
                    gaps.append(
                        {
                            "id": "_shared",
                            "kind": "shared_not_in_api",
                            "detail": f"API_PATHS `{sp}` に対応する API ルートが見つからない",
                        }
                    )

    return gaps


def try_fastapi_openapi() -> dict[str, Any] | None:
    """可能なら実行時 OpenAPI を取得（秘密は含まない）。失敗時は None。"""
    api_root = str(ROOT / "apps" / "api")
    if api_root not in sys.path:
        sys.path.insert(0, api_root)
    try:
        from app.main import app  # type: ignore

        return app.openapi()
    except Exception as exc:  # noqa: BLE001 — ドキュメント生成は落とさない
        print(f"warn: FastAPI OpenAPI 取得スキップ ({exc.__class__.__name__})")
        return None


def build_static_openapi(api_routes: list[dict[str, str]]) -> dict[str, Any]:
    paths: dict[str, Any] = {}
    for r in api_routes:
        path = r["path"]
        method = r["method"].lower()
        paths.setdefault(path, {})
        paths[path][method] = {
            "summary": f"{r['method']} {path}",
            "responses": {"200": {"description": "as-built (static extract)"}},
            "x-source-file": r["file"],
        }
    return {
        "openapi": "3.0.3",
        "info": {
            "title": "oshi-app API (as-built)",
            "version": "generated",
            "description": "静的抽出または FastAPI openapi()。手編集禁止。",
        },
        "paths": paths,
    }


def write_md(name: str, body: str) -> None:
    GEN.mkdir(parents=True, exist_ok=True)
    (GEN / name).write_text(HEADER + body, encoding="utf-8")


def render_web_md(routes: list[dict[str, str]]) -> str:
    lines = [
        "# Web ルート（as-built）\n",
        f"生成時刻 (UTC): `{utc_now()}`\n",
        "| Path | Kind | File |",
        "|------|------|------|",
    ]
    for r in routes:
        lines.append(f"| `{r['path']}` | {r['kind']} | `{r['file']}` |")
    lines.append("")
    return "\n".join(lines)


def render_api_md(routes: list[dict[str, str]]) -> str:
    lines = [
        "# API ルート（as-built）\n",
        f"生成時刻 (UTC): `{utc_now()}`\n",
        "静的抽出。正式なスキーマは `openapi.asbuilt.json` を優先。\n",
        "| Method | Path | File |",
        "|--------|------|------|",
    ]
    for r in routes:
        lines.append(f"| {r['method']} | `{r['path']}` | `{r['file']}` |")
    lines.append("")
    return "\n".join(lines)


def render_shared_md(paths: list[dict[str, str]]) -> str:
    lines = [
        "# Shared API_PATHS（as-built）\n",
        f"生成時刻 (UTC): `{utc_now()}`\n",
        "| Key | Path |",
        "|-----|------|",
    ]
    for p in paths:
        lines.append(f"| `{p['key']}` | `{p['path']}` |")
    lines.append("")
    return "\n".join(lines)


def render_services_md(services: list[dict[str, str]]) -> str:
    lines = [
        "# API services（as-built）\n",
        f"生成時刻 (UTC): `{utc_now()}`\n",
        "| Service | File |",
        "|---------|------|",
    ]
    for s in services:
        lines.append(f"| `{s['name']}` | `{s['file']}` |")
    lines.append("")
    return "\n".join(lines)


def render_gaps_md(gaps: list[dict[str, str]], features: list[dict[str, Any]]) -> str:
    lines = [
        "# ギャップ（feature_status ↔ as-built）\n",
        f"生成時刻 (UTC): `{utc_now()}`\n",
        "検査内容: evidence ファイル、expected_web/api_paths、"
        "planned/deferred の勝手実装、shared↔API の欠落。\n",
    ]
    if not gaps:
        lines.append("問題なし（検出ゼロ）。\n")
    else:
        lines.extend(["| Feature | Kind | Detail |", "|---------|------|--------|"])
        for g in gaps:
            lines.append(f"| `{g['id']}` | {g['kind']} | {g['detail']} |")
        lines.append("")

    lines.append("## ステータス要約\n")
    counts: dict[str, int] = {}
    for f in features:
        st = str(f.get("status") or "?")
        counts[st] = counts.get(st, 0) + 1
    for st, n in sorted(counts.items()):
        lines.append(f"- `{st}`: {n}")
    lines.append("")
    return "\n".join(lines)


def render_openapi_md(openapi: dict[str, Any], source: str) -> str:
    paths = openapi.get("paths") or {}
    lines = [
        "# API OpenAPI カタログ（as-built）\n",
        f"生成時刻 (UTC): `{utc_now()}`\n",
        f"ソース: `{source}`。機械可読は `openapi.asbuilt.json`。\n",
        "| Path | Methods |",
        "|------|---------|",
    ]
    for path in sorted(paths.keys()):
        methods = ", ".join(sorted(m.upper() for m in paths[path].keys() if not m.startswith("x-")))
        lines.append(f"| `{path}` | {methods} |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    web = scan_web_routes()
    api = scan_api_routes()
    shared = scan_shared_paths()
    services = scan_services()
    features = load_features()

    web_paths = {r["path"] for r in web}
    api_paths = {r["path"] for r in api}
    shared_paths = {p["path"] for p in shared}
    gaps = compute_gaps(features, web_paths, api_paths, shared_paths)

    live = try_fastapi_openapi()
    if live is not None:
        openapi = live
        openapi_source = "fastapi.app.openapi()"
    else:
        openapi = build_static_openapi(api)
        openapi_source = "static router extract"

    GEN.mkdir(parents=True, exist_ok=True)
    write_md("web_routes.md", render_web_md(web))
    write_md("api_routes.md", render_api_md(api))
    write_md("shared_paths.md", render_shared_md(shared))
    write_md("services.md", render_services_md(services))
    write_md("gaps.md", render_gaps_md(gaps, features))
    write_md("api_openapi.md", render_openapi_md(openapi, openapi_source))

    (GEN / "openapi.asbuilt.json").write_text(
        json.dumps(openapi, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    inventory = {
        "generated_at": utc_now(),
        "openapi_source": openapi_source,
        "web_routes": web,
        "api_routes": api,
        "shared_paths": shared,
        "services": services,
        "gaps": gaps,
        "feature_count": len(features),
    }
    (GEN / "inventory.json").write_text(
        json.dumps(inventory, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(
        f"OK: web={len(web)} api={len(api)} shared={len(shared)} "
        f"services={len(services)} gaps={len(gaps)} openapi={openapi_source} → {GEN}"
    )


if __name__ == "__main__":
    main()
