#!/usr/bin/env python3
"""ライブ DB（または snapshot JSON）から docs/db/generated/* を再生成する。

使い方:
  # 推奨: DATABASE_URL（Postgres 接続文字列）があるとき
  python scripts/generate_db_docs.py

  # MCP 等で取った snapshot から（秘密不要）
  python scripts/generate_db_docs.py --snapshot docs/db/generated/schema_snapshot.json

環境変数:
  DATABASE_URL または SUPABASE_DB_URL
  （任意）apps/api/.env から上記を読む

出力はすべて GENERATED。手で編集しないこと。
表の wired 状態は docs/db/meta/table_labels.json。
列・表の日本語表示は term_glossary.json + 規則で自動合成（人間は触らない）。
"""

from __future__ import annotations

import argparse
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GEN = ROOT / "docs" / "db" / "generated"
META = ROOT / "docs" / "db" / "meta" / "table_labels.json"
GLOSSARY = ROOT / "docs" / "db" / "meta" / "term_glossary.json"
HEADER = (
    "<!-- GENERATED by scripts/generate_db_docs.py — 手編集禁止。"
    " 再生成: python scripts/generate_db_docs.py -->\n"
)


def _load_dotenv_api() -> None:
    env_path = ROOT / "apps" / "api" / ".env"
    if not env_path.is_file():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        k, v = k.strip(), v.strip().strip('"').strip("'")
        if k in ("DATABASE_URL", "SUPABASE_DB_URL") and k not in os.environ:
            os.environ[k] = v


def fetch_snapshot_from_db(url: str) -> dict:
    try:
        import psycopg
    except ImportError as exc:
        raise SystemExit(
            "psycopg が必要です: pip install 'psycopg[binary]'\n" + str(exc)
        ) from exc

    sql = r"""
    select json_build_object(
      'tables', (select json_agg(t order by t->>'table_name') from (
        select json_build_object('table_name', c.relname, 'comment', obj_description(c.oid), 'columns', (
          select json_agg(json_build_object(
            'column', a.attname,
            'type', pg_catalog.format_type(a.atttypid, a.atttypmod),
            'not_null', a.attnotnull,
            'default', pg_get_expr(ad.adbin, ad.adrelid)
          ) order by a.attnum)
          from pg_attribute a
          left join pg_attrdef ad on a.attrelid=ad.adrelid and a.attnum=ad.adnum
          where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped
        )) as t
        from pg_class c
        join pg_namespace n on n.oid=c.relnamespace
        where n.nspname='public' and c.relkind='r'
      ) s),
      'indexes', (select json_agg(json_build_object(
          'tablename', tablename, 'indexname', indexname, 'indexdef', indexdef
        ) order by tablename, indexname)
        from pg_indexes where schemaname='public'),
      'grants', (select json_agg(json_build_object(
          'grantee', grantee, 'table_name', table_name, 'privs', privs
        ) order by table_name, grantee) from (
          select grantee, table_name,
            string_agg(privilege_type, ',' order by privilege_type) as privs
          from information_schema.role_table_grants
          where table_schema='public'
            and grantee in ('anon','authenticated','service_role')
          group by grantee, table_name
        ) g),
      'policies', (select json_agg(json_build_object(
          'table_name', c.relname, 'polname', pol.polname, 'polcmd', pol.polcmd,
          'using_expr', pg_get_expr(pol.polqual, pol.polrelid),
          'with_check', pg_get_expr(pol.polwithcheck, pol.polrelid)
        ) order by c.relname, pol.polname)
        from pg_policy pol
        join pg_class c on c.oid=pol.polrelid
        join pg_namespace n on n.oid=c.relnamespace
        where n.nspname='public'),
      'fks', (select json_agg(json_build_object(
          'table_name', tc.table_name, 'constraint_name', tc.constraint_name,
          'column_name', kcu.column_name, 'foreign_table', ccu.table_name,
          'foreign_column', ccu.column_name,
          'definition', pg_get_constraintdef(pgc.oid)
        ) order by tc.table_name)
        from information_schema.table_constraints tc
        join pg_constraint pgc on pgc.conname=tc.constraint_name and pgc.contype='f'
        join information_schema.key_column_usage kcu
          on tc.constraint_name=kcu.constraint_name and tc.table_schema=kcu.table_schema
        left join information_schema.constraint_column_usage ccu
          on ccu.constraint_name=tc.constraint_name and ccu.table_schema=tc.table_schema
        where tc.table_schema='public' and tc.constraint_type='FOREIGN KEY'),
      'checks', (select json_agg(json_build_object(
          'table_name', rel.relname, 'constraint_name', con.conname,
          'definition', pg_get_constraintdef(con.oid)
        ) order by rel.relname)
        from pg_constraint con
        join pg_class rel on rel.oid=con.conrelid
        join pg_namespace n on n.oid=rel.relnamespace
        where n.nspname='public' and con.contype='c')
    ) as snapshot;
    """
    with psycopg.connect(url) as conn:
        with conn.cursor() as cur:
            cur.execute(sql)
            row = cur.fetchone()
            return row[0]


def load_labels() -> dict:
    if META.is_file():
        return json.loads(META.read_text(encoding="utf-8"))
    return {}


def load_glossary() -> dict[str, str]:
    if not GLOSSARY.is_file():
        return {}
    data = json.loads(GLOSSARY.read_text(encoding="utf-8"))
    phrases = data.get("phrases") or {}
    return {str(k): str(v) for k, v in phrases.items() if not str(k).startswith("_")}


def translate_identifier(name: str, phrases: dict[str, str], unknown: set[str]) -> str:
    """snake_case 物理名 → 日本語（最長一致）。未知トークンは [token] を残す。"""
    if not name:
        return ""
    if name in phrases:
        return phrases[name]
    remaining = name
    parts: list[str] = []
    ordered = sorted(phrases.keys(), key=len, reverse=True)
    while remaining:
        matched = False
        for phrase in ordered:
            if remaining == phrase or remaining.startswith(phrase + "_"):
                parts.append(phrases[phrase])
                remaining = remaining[len(phrase) :].lstrip("_")
                matched = True
                break
        if matched:
            continue
        tok, _, rest = remaining.partition("_")
        unknown.add(tok)
        parts.append(f"[{tok}]")
        remaining = rest
    return "".join(parts)


def table_ja(name: str, labels: dict, phrases: dict[str, str], unknown: set[str]) -> str:
    meta = labels.get(name) or {}
    if meta.get("ja"):
        return str(meta["ja"])
    return translate_identifier(name, phrases, unknown)


def column_role_hint(col: str, typ: str) -> str:
    """命名規則からの短い意味ヒント（エージェント説明用）。"""
    if col == "members_id":
        return "テナント（ログインユーザー = auth.uid()）"
    if col.endswith("_id"):
        return "識別子または外部キー"
    if col.endswith("_flag"):
        return "真偽・0/1 フラグ"
    if col.endswith("_at"):
        return "タイムスタンプ（時刻付き）"
    if col.endswith("_date"):
        return "日付"
    if col.endswith("_url"):
        return "URL またはパス"
    if col == "slot":
        return "枠番号（プリセット等）"
    if col == "display_order":
        return "表示並び順"
    if "uuid" in typ:
        return "UUID"
    return ""


def write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER + body, encoding="utf-8")


def render_catalog_tables(
    snap: dict, labels: dict, phrases: dict[str, str], unknown: set[str]
) -> str:
    lines = [
        "# 生成: テーブル一覧（物理）",
        "",
        f"生成日時(UTC): `{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%SZ')}`",
        "",
        "| 状態 | 日本語名 | 物理名 | 列数 |",
        "|------|----------|--------|------|",
    ]
    for t in snap.get("tables") or []:
        name = t["table_name"]
        meta = labels.get(name, {})
        ja = table_ja(name, labels, phrases, unknown)
        status = meta.get("status", "schema_ready")
        ncols = len(t.get("columns") or [])
        lines.append(f"| {status} | {ja} | `{name}` | {ncols} |")
    lines.append("")
    lines.append(
        "日本語表示は `term_glossary.json` から自動合成。"
        " wired 状態の正: `docs/db/meta/table_labels.json`"
    )
    lines.append("")
    return "\n".join(lines)


def render_columns(
    snap: dict, labels: dict, phrases: dict[str, str], unknown: set[str]
) -> str:
    lines = [
        "# 生成: 列一覧（日本語列名付き）",
        "",
        "日本語列名は英語物理名から **自動合成**（手編集禁止）。"
        " 読み方の本文: [schema_guide.md](schema_guide.md)",
        "",
    ]
    for t in snap.get("tables") or []:
        name = t["table_name"]
        ja = table_ja(name, labels, phrases, unknown)
        lines.append(f"## `{name}`（{ja}）")
        lines.append("")
        lines.append("| 日本語列名 | 物理名 | 型 | NULL | default |")
        lines.append("|------------|--------|----|------|---------|")
        for c in t.get("columns") or []:
            col = c["column"]
            col_ja = translate_identifier(col, phrases, unknown)
            nn = "NO" if c.get("not_null") else "YES"
            default = c.get("default") or ""
            if len(str(default)) > 60:
                default = str(default)[:57] + "..."
            if default:
                lines.append(
                    f"| {col_ja} | `{col}` | `{c['type']}` | {nn} | `{default}` |"
                )
            else:
                lines.append(f"| {col_ja} | `{col}` | `{c['type']}` | {nn} | |")
        lines.append("")
    return "\n".join(lines)


def render_schema_guide(
    snap: dict, labels: dict, phrases: dict[str, str], unknown: set[str]
) -> str:
    """人間・エージェント向け: 表と列の意味を日本語で説明する資料。"""
    lines = [
        "# 生成: スキーマ読み下し（日本語）",
        "",
        "コード・SQL は英語物理名。**このファイルは意味の説明用**（自動生成）。",
        "",
        f"生成日時(UTC): `{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%SZ')}`",
        "",
        "## 使い方",
        "",
        "- エージェントはユーザーに表・列を説明するとき **ここを正** にする",
        "- プレビューで図を見る: [er-diagram.md](er-diagram.md)（`Ctrl+Shift+V`）",
        "- 詳細型・制約: [columns.md](columns.md) / [constraints.md](constraints.md)",
        "",
    ]
    for t in snap.get("tables") or []:
        name = t["table_name"]
        meta = labels.get(name, {})
        ja = table_ja(name, labels, phrases, unknown)
        status = meta.get("status", "schema_ready")
        status_ja = {
            "wired": "アプリ連携済み（API 可）",
            "schema_ready": "DB のみ・未連携（Data API 不可）",
            "storage": "Storage 連携",
        }.get(status, status)
        lines.append(f"## {ja}（`{name}`）")
        lines.append("")
        lines.append(f"- **状態:** {status_ja}（`{status}`）")
        lines.append(f"- **列数:** {len(t.get('columns') or [])}")
        lines.append("")
        lines.append("| 日本語列名 | 物理名 | 型 | 補足 |")
        lines.append("|------------|--------|----|------|")
        for c in t.get("columns") or []:
            col = c["column"]
            col_ja = translate_identifier(col, phrases, unknown)
            hint = column_role_hint(col, c.get("type") or "")
            lines.append(f"| {col_ja} | `{col}` | `{c['type']}` | {hint} |")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "未知トークンが残る場合は `docs/db/meta/term_glossary.json` に追加して再生成"
        "（エージェント作業。人間は触らない）。"
    )
    lines.append("")
    return "\n".join(lines)


def render_unknown_terms(unknown: set[str]) -> str:
    lines = [
        "# 生成: 用語辞書で未登録のトークン",
        "",
        "空なら問題なし。行がある場合はエージェントが"
        " `docs/db/meta/term_glossary.json` の `phrases` に追加して再生成する。",
        "",
    ]
    if not unknown:
        lines.append("（なし）")
        lines.append("")
        return "\n".join(lines)
    lines.append("| トークン |")
    lines.append("|----------|")
    for tok in sorted(unknown):
        lines.append(f"| `{tok}` |")
    lines.append("")
    return "\n".join(lines)


def render_constraints(snap: dict) -> str:
    lines = [
        "# 生成: CHECK / UNIQUE インデックス / FK",
        "",
        "## CHECK",
        "",
        "| 表 | 制約 | 定義 |",
        "|----|------|------|",
    ]
    for c in snap.get("checks") or []:
        lines.append(
            f"| `{c['table_name']}` | `{c['constraint_name']}` | `{c['definition']}` |"
        )
    lines += ["", "## 外部キー（抜粋）", "", "| From | To | 定義 |", "|------|----|------|"]
    seen = set()
    for fk in snap.get("fks") or []:
        key = (fk.get("table_name"), fk.get("constraint_name"), fk.get("definition"))
        if key in seen:
            continue
        seen.add(key)
        ft = fk.get("foreign_table") or "?"
        lines.append(
            f"| `{fk['table_name']}` | `{ft}` | `{fk.get('definition','')}` |"
        )
    lines += ["", "## インデックス", "", "| 表 | 名前 | 定義 |", "|----|------|------|"]
    for ix in snap.get("indexes") or []:
        lines.append(
            f"| `{ix['tablename']}` | `{ix['indexname']}` | `{ix['indexdef']}` |"
        )
    lines.append("")
    return "\n".join(lines)


def render_grants_policies(snap: dict) -> str:
    lines = [
        "# 生成: GRANT / RLS ポリシー",
        "",
        "## GRANT（anon / authenticated / service_role）",
        "",
        "| 役割 | 表 | 権限 |",
        "|------|----|------|",
    ]
    for g in snap.get("grants") or []:
        lines.append(
            f"| `{g['grantee']}` | `{g['table_name']}` | `{g['privs']}` |"
        )
    lines += [
        "",
        "## RLS ポリシー",
        "",
        "| 表 | 名前 | cmd | USING | WITH CHECK |",
        "|----|------|-----|-------|------------|",
    ]
    for p in snap.get("policies") or []:
        lines.append(
            f"| `{p['table_name']}` | `{p['polname']}` | `{p['polcmd']}` | "
            f"`{p.get('using_expr') or ''}` | `{p.get('with_check') or ''}` |"
        )
    lines.append("")
    return "\n".join(lines)


def render_er(
    snap: dict, labels: dict, phrases: dict[str, str], unknown: set[str]
) -> str:
    lines = [
        "# 生成: ER 図（Mermaid）",
        "",
        "グッズ管理の中心は `registered_product`（登録製品）。",
        "",
        "```mermaid",
        "erDiagram",
    ]
    interesting = set()
    for fk in snap.get("fks") or []:
        a, b = fk.get("table_name"), fk.get("foreign_table")
        if a:
            interesting.add(a)
        if b:
            interesting.add(b)
    for name, meta in labels.items():
        if meta.get("status") == "wired":
            interesting.add(name)

    for name in sorted(interesting):
        if name.startswith("auth"):
            continue
        ja = table_ja(name, labels, phrases, unknown)
        safe = re.sub(r"[^a-zA-Z0-9_]", "_", name)
        lines.append(f'  {safe}["{name} / {ja}"]')

    seen_edge = set()
    for fk in snap.get("fks") or []:
        a, b = fk.get("table_name"), fk.get("foreign_table")
        if not a or not b or b.startswith("auth") or a not in interesting:
            continue
        if b not in interesting:
            continue
        sa = re.sub(r"[^a-zA-Z0-9_]", "_", a)
        sb = re.sub(r"[^a-zA-Z0-9_]", "_", b)
        edge = (sa, sb, fk.get("column_name"))
        if edge in seen_edge:
            continue
        seen_edge.add(edge)
        col = fk.get("column_name") or "fk"
        lines.append(f"  {sa} }}o--|| {sb} : {col}")

    lines.append("```")
    lines.append("")
    lines.append("手書きの補足・読み方: [../er-overview.md](../er-overview.md)")
    lines.append("")
    lines.append("プレビューは `Ctrl+Shift+V`（クラシック Markdown）。右上 Preview では図にならない。")
    lines.append("")
    return "\n".join(lines)


def render_baseline_sql(snap: dict) -> str:
    """ドキュメント用の簡易 CREATE（完全再現保証ではない）。"""
    lines = [
        "-- GENERATED schema baseline (documentation / disaster reference)",
        "-- 既存プロジェクトへの再適用用ではない。正の変更は supabase/migrations/ へ。",
        f"-- generated_at_utc: {datetime.now(timezone.utc).isoformat()}",
        "",
    ]
    for t in snap.get("tables") or []:
        name = t["table_name"]
        qname = f'"{name}"' if name == "character" else name
        lines.append(f"-- === {name} ===")
        lines.append(f"CREATE TABLE IF NOT EXISTS public.{qname} (")
        col_sql = []
        for c in t.get("columns") or []:
            nn = " NOT NULL" if c.get("not_null") else ""
            default = f" DEFAULT {c['default']}" if c.get("default") else ""
            col_sql.append(f"  {c['column']} {c['type']}{nn}{default}")
        lines.append(",\n".join(col_sql))
        lines.append(");")
        lines.append("")
    lines.append("-- indexes / constraints: see constraints.md（生成）と migrations")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--snapshot",
        type=Path,
        help="schema_snapshot.json（省略時は DB 接続）",
    )
    args = parser.parse_args()
    _load_dotenv_api()

    if args.snapshot:
        snap = json.loads(args.snapshot.read_text(encoding="utf-8"))
    else:
        url = os.environ.get("DATABASE_URL") or os.environ.get("SUPABASE_DB_URL")
        if not url:
            raise SystemExit(
                "DATABASE_URL / SUPABASE_DB_URL が無い場合は "
                "--snapshot docs/db/generated/schema_snapshot.json を指定してください。"
            )
        snap = fetch_snapshot_from_db(url)
        (GEN / "schema_snapshot.json").write_text(
            json.dumps(snap, ensure_ascii=False, indent=2), encoding="utf-8"
        )

    labels = load_labels()
    phrases = load_glossary()
    unknown: set[str] = set()
    GEN.mkdir(parents=True, exist_ok=True)

    write(GEN / "tables.md", render_catalog_tables(snap, labels, phrases, unknown))
    write(GEN / "columns.md", render_columns(snap, labels, phrases, unknown))
    write(GEN / "schema_guide.md", render_schema_guide(snap, labels, phrases, unknown))
    write(GEN / "unknown_terms.md", render_unknown_terms(unknown))
    write(GEN / "constraints.md", render_constraints(snap))
    write(GEN / "grants_policies.md", render_grants_policies(snap))
    write(GEN / "er-diagram.md", render_er(snap, labels, phrases, unknown))
    (GEN / "schema_baseline.sql").write_text(
        HEADER.replace("<!--", "--").replace("-->", "")
        + "\n"
        + render_baseline_sql(snap),
        encoding="utf-8",
    )
    write(
        GEN / "README.md",
        "\n".join(
            [
                "# generated/（自動生成）",
                "",
                "このディレクトリは **手編集禁止**。",
                "",
                "```powershell",
                "python scripts/generate_db_docs.py --snapshot docs/db/generated/schema_snapshot.json",
                "# または DATABASE_URL をセットして",
                "python scripts/generate_db_docs.py",
                "```",
                "",
                "| ファイル | 内容 |",
                "|----------|------|",
                "| `schema_guide.md` | **表・列の日本語読み下し（説明の正）** |",
                "| `columns.md` | 列一覧 + 日本語列名 |",
                "| `tables.md` | 表一覧 + 日本語名 |",
                "| `unknown_terms.md` | 用語未登録トークン（あればエージェントが glossary 更新） |",
                "| `schema_snapshot.json` | 生データ |",
                "| `schema_baseline.sql` | ドキュメント用 CREATE 一覧 |",
                "| `constraints.md` | CHECK / FK / INDEX |",
                "| `grants_policies.md` | GRANT / RLS |",
                "| `er-diagram.md` | Mermaid ER（`Ctrl+Shift+V`） |",
                "",
                "用語辞書（エージェント更新）: `../meta/term_glossary.json`",
                "wired 状態: `../meta/table_labels.json`",
                "",
            ]
        ),
    )
    print("generated ->", GEN)
    if unknown:
        print("WARNING unknown tokens:", ", ".join(sorted(unknown)))
        print("  -> docs/db/meta/term_glossary.json に追加して再実行")
    else:
        print("unknown tokens: (none)")


if __name__ == "__main__":
    main()
