#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""サードパーティ／外部サービス NOTICE を生成し、docs と Web 公開ページ用 JSON を同期する。

使い方:
  python scripts/generate_third_party_notices.py
  python scripts/generate_third_party_notices.py --check

正本（手）: docs/legal/services.json（外部 API・ブランド表示メモ）
自動: docs/legal/generated/* と apps/web/src/data/generated/third_party_notices.json
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DOCS_LEGAL = ROOT / "docs" / "legal"
DOCS_GEN = DOCS_LEGAL / "generated"
WEB_GEN = ROOT / "apps" / "web" / "src" / "data" / "generated"
SERVICES_PATH = DOCS_LEGAL / "services.json"

NPM_PACKAGE_JSONS = (
    ROOT / "apps" / "web" / "package.json",
    ROOT / "packages" / "shared" / "package.json",
)
PIP_REQUIREMENTS = ROOT / "apps" / "api" / "requirements.txt"

HEADER_MD = (
    "<!-- GENERATED by scripts/generate_third_party_notices.py — 手編集禁止。"
    " 再生成: python scripts/generate_third_party_notices.py -->\n"
)

APP_NOTICE_JA = (
    "oshi-app 本体のソースコードは All Rights Reserved（リポジトリ直下 LICENSE）です。"
    "本ページは、アプリが利用するオープンソース依存と、外部サービスの表示メモを掲示します。"
)

# pnpm workspace 内製パッケージは OSS 一覧から除外
SKIP_NPM_NAMES = {"@oshi/shared", "oshi-app", "web", "shared"}


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _license_to_str(value: Any) -> str:
    if value is None:
        return "UNKNOWN"
    if isinstance(value, str):
        s = value.strip()
        return s or "UNKNOWN"
    if isinstance(value, dict):
        t = value.get("type")
        if isinstance(t, str) and t.strip():
            return t.strip()
    if isinstance(value, list):
        parts = [_license_to_str(x) for x in value]
        parts = [p for p in parts if p != "UNKNOWN"]
        return " OR ".join(parts) if parts else "UNKNOWN"
    return str(value)


def load_services() -> list[dict[str, Any]]:
    if not SERVICES_PATH.is_file():
        return []
    data = json.loads(SERVICES_PATH.read_text(encoding="utf-8"))
    items = data.get("services") if isinstance(data, dict) else data
    if not isinstance(items, list):
        return []
    return [x for x in items if isinstance(x, dict)]


def read_direct_npm_deps() -> dict[str, str]:
    """package.json の dependencies（version range）を集約。"""
    out: dict[str, str] = {}
    for path in NPM_PACKAGE_JSONS:
        if not path.is_file():
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        deps = data.get("dependencies") or {}
        if not isinstance(deps, dict):
            continue
        for name, ver in deps.items():
            if name in SKIP_NPM_NAMES:
                continue
            if isinstance(name, str) and isinstance(ver, str):
                out[name] = ver
    return out


def _read_pkg_json(path: Path) -> dict[str, Any] | None:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return data if isinstance(data, dict) else None


def collect_npm_from_node_modules() -> list[dict[str, Any]]:
    """apps/web/node_modules 配下の package.json から本番依存を拾う（pnpm 対応）。"""
    nm = ROOT / "apps" / "web" / "node_modules"
    if not nm.is_dir():
        return []

    by_name: dict[str, dict[str, Any]] = {}
    direct = read_direct_npm_deps()

    candidates: list[Path] = []
    # 通常リンク
    for child in nm.iterdir():
        if child.name.startswith("."):
            continue
        if child.name.startswith("@"):
            if child.is_dir():
                for scoped in child.iterdir():
                    candidates.append(scoped / "package.json")
        else:
            candidates.append(child / "package.json")
    # pnpm 実体
    pnpm = nm / ".pnpm"
    if pnpm.is_dir():
        for pkg_json in pnpm.glob("*/node_modules/*/package.json"):
            candidates.append(pkg_json)
        for pkg_json in pnpm.glob("*/node_modules/@*/*/package.json"):
            candidates.append(pkg_json)

    for pkg_json in candidates:
        data = _read_pkg_json(pkg_json)
        if not data:
            continue
        name = data.get("name")
        if not isinstance(name, str) or name in SKIP_NPM_NAMES:
            continue
        # 直接依存のみを一覧の主対象にする（推移的は肥大化しやすい）
        if name not in direct:
            continue
        version = data.get("version")
        ver = version if isinstance(version, str) else direct.get(name, "")
        homepage = data.get("homepage")
        home = homepage if isinstance(homepage, str) else ""
        lic = _license_to_str(data.get("license"))
        prev = by_name.get(name)
        row = {
            "name": name,
            "version": ver,
            "license": lic,
            "ecosystem": "npm",
            "homepage": home,
        }
        if prev is None or (prev.get("license") == "UNKNOWN" and lic != "UNKNOWN"):
            by_name[name] = row

    return list(by_name.values())


def collect_npm_via_pnpm() -> list[dict[str, Any]]:
    """pnpm licenses list --json（利用可能なとき）。"""
    try:
        proc = subprocess.run(
            ["pnpm", "licenses", "list", "--json", "--prod"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            check=False,
            timeout=120,
        )
    except (OSError, subprocess.TimeoutExpired):
        return []
    if proc.returncode != 0 or not proc.stdout.strip():
        return []
    try:
        data = json.loads(proc.stdout)
    except json.JSONDecodeError:
        return []

    direct = read_direct_npm_deps()
    by_name: dict[str, dict[str, Any]] = {}

    # pnpm の JSON 形はバージョンにより異なる。よくあるのは license → packages[]
    if isinstance(data, dict):
        for license_name, packages in data.items():
            if not isinstance(packages, list):
                continue
            for pkg in packages:
                if not isinstance(pkg, dict):
                    continue
                name = pkg.get("name") or pkg.get("packageName")
                if not isinstance(name, str) or name in SKIP_NPM_NAMES:
                    continue
                if name not in direct:
                    continue
                version = pkg.get("version") or pkg.get("versions") or ""
                if isinstance(version, list):
                    version = version[0] if version else ""
                if not isinstance(version, str):
                    version = str(version)
                homepage = pkg.get("homepage") or pkg.get("repository") or ""
                if not isinstance(homepage, str):
                    homepage = ""
                by_name[name] = {
                    "name": name,
                    "version": version or direct.get(name, ""),
                    "license": _license_to_str(license_name),
                    "ecosystem": "npm",
                    "homepage": homepage,
                }
    return list(by_name.values())


def collect_npm_from_package_json_only() -> list[dict[str, Any]]:
    """node_modules が無いときの最低限（ライセンスは UNKNOWN）。"""
    return [
        {
            "name": name,
            "version": ver,
            "license": "UNKNOWN",
            "ecosystem": "npm",
            "homepage": "",
        }
        for name, ver in sorted(read_direct_npm_deps().items())
    ]


def collect_npm_packages() -> list[dict[str, Any]]:
    via_pnpm = collect_npm_via_pnpm()
    if via_pnpm:
        return via_pnpm
    via_nm = collect_npm_from_node_modules()
    if via_nm:
        return via_nm
    return collect_npm_from_package_json_only()


_REQ_NAME_RE = re.compile(r"^[A-Za-z0-9_.-]+$")


def parse_requirements_names(text: str) -> list[str]:
    return [row["name"] for row in parse_requirements_rows(text)]


def parse_requirements_rows(text: str) -> list[dict[str, str]]:
    """requirements.txt から名前と版制約を決定的に抽出（CI/OS 差分を避ける）。"""
    rows: list[dict[str, str]] = []
    seen: set[str] = set()
    for line in text.splitlines():
        raw = line.strip()
        if not raw or raw.startswith("#") or raw.startswith("-"):
            continue
        base = raw.split(";", 1)[0].strip()
        name = re.split(r"[<>=!~\[]", base, maxsplit=1)[0].strip()
        if not name or not _REQ_NAME_RE.match(name):
            continue
        key = name.lower()
        if key in seen:
            continue
        seen.add(key)
        constraint = base[len(name) :].strip()
        rows.append({"name": name, "constraint": constraint})
    return rows


def collect_pip_packages() -> list[dict[str, Any]]:
    if not PIP_REQUIREMENTS.is_file():
        return []
    rows: list[dict[str, Any]] = []
    for item in parse_requirements_rows(PIP_REQUIREMENTS.read_text(encoding="utf-8")):
        name = item["name"]
        # テスト専用は一覧から外す（実行時配布物ではない）
        if name.lower() in {"pytest", "pytest-asyncio"}:
            continue
        rows.append(
            {
                "name": name,
                "version": item["constraint"],
                "license": "UNKNOWN",
                "ecosystem": "pip",
                "homepage": "",
            }
        )
    return rows


def build_payload(
    packages: list[dict[str, Any]],
    services: list[dict[str, Any]],
    *,
    generated_at: str,
) -> dict[str, Any]:
    sorted_pkgs = sorted(
        packages,
        key=lambda p: (str(p.get("ecosystem", "")), str(p.get("name", "")).lower()),
    )
    return {
        "generated_at": generated_at,
        "app_notice_ja": APP_NOTICE_JA,
        "packages": sorted_pkgs,
        "services": services,
    }


def render_markdown(payload: dict[str, Any]) -> str:
    lines: list[str] = [
        HEADER_MD,
        "<!-- 更新: 自動 — 手編集禁止。凡例: docs/README.md -->",
        "",
        "# サードパーティ／外部サービス NOTICE",
        "",
        f"生成時刻 (UTC): `{payload.get('generated_at', '')}`",
        "",
        "## アプリ本体",
        "",
        str(payload.get("app_notice_ja", "")),
        "",
        "## オープンソース依存",
        "",
        "| 名前 | 版 | ライセンス | 系統 |",
        "|------|----|------------|------|",
    ]
    for p in payload.get("packages") or []:
        if not isinstance(p, dict):
            continue
        lines.append(
            f"| {p.get('name', '')} | {p.get('version', '')} | "
            f"{p.get('license', '')} | {p.get('ecosystem', '')} |"
        )
    lines.extend(
        [
            "",
            "## 外部サービス（表示・規約メモ）",
            "",
            "OSS 一覧とは別に、API／ブランドガイドライン上の表示義務を管理する。",
            "",
        ]
    )
    for s in payload.get("services") or []:
        if not isinstance(s, dict):
            continue
        name = s.get("name_ja") or s.get("id") or ""
        status = s.get("status") or ""
        note = s.get("note_ja") or ""
        req = "要表示" if s.get("attribution_required") else "表示義務なし（メモ）"
        lines.append(f"### {name}")
        lines.append("")
        lines.append(f"- 状態: `{status}` · {req}")
        if note:
            lines.append(f"- {note}")
        docs_url = s.get("docs_url")
        if isinstance(docs_url, str) and docs_url:
            lines.append(f"- 参考: {docs_url}")
        lines.append("")
    lines.append(
        "再生成: `python scripts/generate_third_party_notices.py`  "
        "（Web 公開ページ `/licenses` も同じ JSON を表示）"
    )
    lines.append("")
    return "\n".join(lines)


def write_outputs(
    payload: dict[str, Any],
    *,
    docs_gen: Path = DOCS_GEN,
    web_gen: Path = WEB_GEN,
) -> None:
    docs_gen.mkdir(parents=True, exist_ok=True)
    web_gen.mkdir(parents=True, exist_ok=True)
    text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    (docs_gen / "third_party_notices.json").write_text(text, encoding="utf-8")
    (web_gen / "third_party_notices.json").write_text(text, encoding="utf-8")
    (docs_gen / "third_party_notices.md").write_text(
        render_markdown(payload), encoding="utf-8"
    )
    readme = docs_gen / "README.md"
    if not readme.is_file():
        readme.write_text(
            "<!-- 更新: 自動フォルダの説明 — 中身の生成物は手編集禁止。凡例: docs/README.md -->\n"
            "# legal/generated\n\n"
            "`python scripts/generate_third_party_notices.py` が出力する。\n"
            "Web は `apps/web/src/data/generated/third_party_notices.json` と同一内容。\n",
            encoding="utf-8",
        )


def normalize_payload_for_check(payload: dict[str, Any]) -> str:
    clone = json.loads(json.dumps(payload))
    clone.pop("generated_at", None)
    return json.dumps(clone, ensure_ascii=False, sort_keys=True, indent=2) + "\n"


def gather_payload(*, generated_at: str | None = None) -> dict[str, Any]:
    packages = collect_npm_packages() + collect_pip_packages()
    return build_payload(
        packages,
        load_services(),
        generated_at=generated_at or utc_now(),
    )


def check_drift() -> int:
    payload = gather_payload(generated_at="1970-01-01T00:00:00Z")
    expected = normalize_payload_for_check(payload)
    paths = (
        DOCS_GEN / "third_party_notices.json",
        WEB_GEN / "third_party_notices.json",
    )
    for path in paths:
        if not path.is_file():
            print(f"missing: {path.relative_to(ROOT).as_posix()}", file=sys.stderr)
            return 1
        current = json.loads(path.read_text(encoding="utf-8"))
        if normalize_payload_for_check(current) != expected:
            print(
                f"drift: {path.relative_to(ROOT).as_posix()} "
                "— python scripts/generate_third_party_notices.py を実行してコミット",
                file=sys.stderr,
            )
            return 1
    # docs と web が一致しているか
    docs_raw = (DOCS_GEN / "third_party_notices.json").read_text(encoding="utf-8")
    web_raw = (WEB_GEN / "third_party_notices.json").read_text(encoding="utf-8")
    if normalize_payload_for_check(json.loads(docs_raw)) != normalize_payload_for_check(
        json.loads(web_raw)
    ):
        print("drift: docs と web の third_party_notices.json が不一致", file=sys.stderr)
        return 1
    print("third-party notices: OK")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="再生成結果とコミット済み JSON の差分を検査（時刻除く）",
    )
    args = parser.parse_args(argv)
    if args.check:
        return check_drift()

    payload = gather_payload()
    write_outputs(payload)
    rel_docs = (DOCS_GEN / "third_party_notices.json").relative_to(ROOT).as_posix()
    rel_web = (WEB_GEN / "third_party_notices.json").relative_to(ROOT).as_posix()
    print(f"wrote {rel_docs}")
    print(f"wrote {rel_web}")
    print(f"packages={len(payload['packages'])} services={len(payload['services'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
