#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""デザイン as-built（gaps / 採用状況）を docs/design/generated/ に出力する。

使い方:
  python scripts/generate_design_docs.py

手編集禁止。正本は docs/design/meta/* と apps/web のコード。
"""

from __future__ import annotations

import importlib.util
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
GEN = ROOT / "docs" / "design" / "generated"
WEB_APP = ROOT / "apps" / "web" / "src" / "app"
ADOPTION = ROOT / "docs" / "design" / "meta" / "design_adoption.json"
ICONS_META = ROOT / "docs" / "design" / "meta" / "icons.json"

HEADER = (
    "<!-- GENERATED by scripts/generate_design_docs.py — 手編集禁止。"
    " 再生成: python scripts/generate_design_docs.py -->\n"
)

HEX_RE = re.compile(r"#[0-9a-fA-F]{3}(?:[0-9a-fA-F]{3})?\b")
HEX_IN_REGEX_RE = re.compile(r"/\#\[0-9A-Fa-f\]")
LUCIDE_DIRECT_RE = re.compile(r"""from\s+['"]lucide-react['"]""")
ICONS_ALIAS_RE = re.compile(r"""from\s+['"]@/lib/icons['"]""")
RAW_BUTTON_RE = re.compile(r"<\s*button\b")

# カラータグ設定など製品ラベル色は hex を gaps の「UI 直書き」から除外
HEX_ALLOW_PATH_PARTS = (
    "/settings/color-tags/",
    "/settings/category-tags/",
)


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def load_compliance_mod():
    script = ROOT / "scripts" / "check_design_compliance.py"
    spec = importlib.util.spec_from_file_location("check_design_compliance", script)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    sys.modules["check_design_compliance"] = mod
    spec.loader.exec_module(mod)
    return mod


def scan_pages() -> list[dict[str, Any]]:
    if not WEB_APP.is_dir():
        return []
    pages: list[dict[str, Any]] = []
    for path in sorted(WEB_APP.rglob("page.tsx")):
        rel = path.relative_to(WEB_APP)
        parts: list[str] = []
        for part in rel.parts[:-1]:
            if part.startswith("(") and part.endswith(")"):
                continue
            # next-intl の [locale] は論理パスから除外（/gallery として記録）
            if part == "[locale]":
                continue
            parts.append(part)
        url = "/" + "/".join(parts) if parts else "/"
        text = path.read_text(encoding="utf-8")
        file_rel = str(path.relative_to(ROOT)).replace("\\", "/")
        url_slash = url if url.endswith("/") else url + "/"
        allow_hex = any(
            allow in url_slash or allow.rstrip("/") == url for allow in HEX_ALLOW_PATH_PARTS
        )

        hex_hits = 0
        for line in text.splitlines():
            if HEX_IN_REGEX_RE.search(line):
                stripped = HEX_IN_REGEX_RE.sub("", line)
                if HEX_RE.search(stripped):
                    hex_hits += 1
            elif HEX_RE.search(line):
                hex_hits += 1
        if allow_hex:
            hex_hits = 0

        pages.append(
            {
                "path": url,
                "file": file_rel,
                "has_hex_ui": hex_hits > 0,
                "hex_line_count": hex_hits,
                "uses_lib_icons": bool(ICONS_ALIAS_RE.search(text)),
                "lucide_direct": bool(LUCIDE_DIRECT_RE.search(text)),
                "raw_button": bool(RAW_BUTTON_RE.search(text)),
                "is_dev": url.startswith("/dev"),
            }
        )
    return pages


def load_adoption() -> dict[str, Any]:
    if not ADOPTION.is_file():
        return {"screens": []}
    return json.loads(ADOPTION.read_text(encoding="utf-8"))


def adoption_by_path(data: dict[str, Any]) -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for s in data.get("screens") or []:
        p = str(s.get("path") or "")
        if p:
            out[p] = s
    return out


def compute_gaps(
    pages: list[dict[str, Any]],
    adoption_map: dict[str, dict[str, Any]],
    compliance_findings: list[Any],
) -> list[dict[str, str]]:
    gaps: list[dict[str, str]] = []

    for p in pages:
        if p["is_dev"]:
            continue
        path = p["path"]
        if p["has_hex_ui"]:
            gaps.append(
                {
                    "id": path,
                    "kind": "hex_in_page",
                    "detail": f"UI hex 直書きの疑い（{p['hex_line_count']} 行）。{p['file']}",
                }
            )
        if p["lucide_direct"]:
            gaps.append(
                {
                    "id": path,
                    "kind": "lucide_direct_import",
                    "detail": f"lucide-react 直 import。@/lib/icons へ。{p['file']}",
                }
            )
        if p["raw_button"]:
            gaps.append(
                {
                    "id": path,
                    "kind": "raw_button",
                    "detail": f"生 <button>。ui/button へ。{p['file']}",
                }
            )

        ad = adoption_map.get(path)
        if ad is not None:
            st = str(ad.get("status") or "not_started")
            if st in ("not_started", "deferred", "partial"):
                gaps.append(
                    {
                        "id": path,
                        "kind": "lab_not_fully_adopted",
                        "detail": f"status=`{st}` lab_variant={ad.get('lab_variant')!r}",
                    }
                )

    for f in compliance_findings:
        if "design-lab" in f.path or "/styles/" in f.path.replace("\\", "/"):
            continue
        gaps.append(
            {
                "id": f.path,
                "kind": f"compliance_{f.kind}",
                "detail": f"L{f.line}: {f.detail}",
            }
        )

    # 重複除去（id+kind）
    seen: set[tuple[str, str]] = set()
    unique: list[dict[str, str]] = []
    for g in gaps:
        key = (g["id"], g["kind"])
        if key in seen:
            continue
        seen.add(key)
        unique.append(g)
    return unique


def render_gaps_md(
    gaps: list[dict[str, str]],
    pages: list[dict[str, Any]],
    adoption: dict[str, Any],
) -> str:
    lines = [
        HEADER,
        "# デザインギャップ（as-built）\n",
        f"生成時刻 (UTC): `{utc_now()}`\n",
        "検査: page.tsx の hex / lucide / raw button、`design_adoption.json`、compliance。\n",
        "**本番 UI を自動では変えない。** 採用は skill `design-adoption`（人の本決定後）。\n",
    ]
    if not gaps:
        lines.append("問題なし（検出ゼロ）。\n")
    else:
        lines.extend(["| ID | Kind | Detail |", "|----|------|--------|"])
        for g in gaps:
            detail = g["detail"].replace("|", "\\|")
            lines.append(f"| `{g['id']}` | {g['kind']} | {detail} |")
        lines.append("")

    lines.append("## Lab 採用状況（meta）\n")
    lines.extend(
        [
            "| Path | status | lab_variant | notes |",
            "|------|--------|-------------|-------|",
        ]
    )
    for s in adoption.get("screens") or []:
        lines.append(
            f"| `{s.get('path')}` | `{s.get('status')}` | "
            f"{s.get('lab_variant')!r} | {s.get('notes_ja') or ''} |"
        )
    lines.append("")

    lines.append("## page.tsx 要約\n")
    prod = [p for p in pages if not p["is_dev"]]
    lines.append(f"- 本番 page 数: {len(prod)}")
    lines.append(f"- `@/lib/icons` 使用: {sum(1 for p in prod if p['uses_lib_icons'])}")
    lines.append(f"- lucide 直 import: {sum(1 for p in prod if p['lucide_direct'])}")
    lines.append(f"- UI hex 疑い: {sum(1 for p in prod if p['has_hex_ui'])}")
    lines.append("")
    return "\n".join(lines)


def render_adoption_md(adoption: dict[str, Any]) -> str:
    lines = [
        HEADER,
        "# Lab → 本番 採用状況\n",
        f"生成時刻 (UTC): `{utc_now()}`\n",
        "正本: `docs/design/meta/design_adoption.json`。更新手順: skill `design-adoption`。\n",
        "| Path | status | lab_variant | updated_at | notes |",
        "|------|--------|-------------|------------|-------|",
    ]
    for s in adoption.get("screens") or []:
        lines.append(
            f"| `{s.get('path')}` | `{s.get('status')}` | {s.get('lab_variant')!r} | "
            f"{s.get('updated_at')!r} | {s.get('notes_ja') or ''} |"
        )
    lines.append("")
    return "\n".join(lines)


def write_md(name: str, body: str) -> None:
    GEN.mkdir(parents=True, exist_ok=True)
    (GEN / name).write_text(body.replace("\r\n", "\n"), encoding="utf-8", newline="\n")


def main() -> int:
    pages = scan_pages()
    adoption = load_adoption()
    adoption_map = adoption_by_path(adoption)

    compliance = load_compliance_mod()
    findings = []
    for path in compliance.iter_source_files(None):
        findings.extend(compliance.scan_file(path))

    gaps = compute_gaps(pages, adoption_map, findings)
    write_md("gaps.md", render_gaps_md(gaps, pages, adoption))
    write_md("adoption_status.md", render_adoption_md(adoption))

    inventory = {
        "generated_at": utc_now(),
        "pages": pages,
        "gaps": gaps,
        "adoption": adoption,
        "icons_catalog_count": None,
    }
    if ICONS_META.is_file():
        icons = json.loads(ICONS_META.read_text(encoding="utf-8"))
        names: set[str] = set()
        for row in icons.get("catalog") or []:
            for n in row.get("icons") or []:
                names.add(n)
        inventory["icons_catalog_count"] = len(names)

    GEN.mkdir(parents=True, exist_ok=True)
    (GEN / "inventory.json").write_text(
        json.dumps(inventory, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {GEN.relative_to(ROOT)} (gaps={len(gaps)}, pages={len(pages)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
