#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""docs/design/meta/lucide_icon_picker.json から共有カタログと icons 同期を生成する。

使い方:
  python scripts/sync_lucide_icon_catalog.py
  python scripts/sync_lucide_icon_catalog.py --check
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
PICKER_JSON = ROOT / "docs" / "design" / "meta" / "lucide_icon_picker.json"
ICONS_JSON = ROOT / "docs" / "design" / "meta" / "icons.json"
SHARED_TS = ROOT / "packages" / "shared" / "src" / "lucide_icon_catalog.ts"
API_PY = ROOT / "apps" / "api" / "app" / "services" / "lucide_icon_catalog.py"

SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def slug_to_pascal(slug: str) -> str:
    return "".join(part.capitalize() for part in slug.split("-"))


def load_picker() -> dict[str, Any]:
    data = json.loads(PICKER_JSON.read_text(encoding="utf-8"))
    for key in (
        "fallbacks",
        "bootstrap_migration",
        "default_category_tags",
        "default_storage_locations",
        "picker",
    ):
        if key not in data:
            raise ValueError(f"lucide_icon_picker.json: {key} が必須")
    return data


def collect_slugs(data: dict[str, Any]) -> list[str]:
    slugs: set[str] = set()
    for group in data["picker"].values():
        for row in group:
            slug = row["slug"]
            if not SLUG_RE.match(slug):
                raise ValueError(f"不正な slug: {slug!r}")
            slugs.add(slug)
    for fb in data["fallbacks"].values():
        slugs.add(fb)
    for mapped in data["bootstrap_migration"].values():
        slugs.add(mapped)
    for row in data["default_category_tags"]:
        slugs.add(row["category_tag_icon"])
    for row in data["default_storage_locations"]:
        slugs.add(row["storage_location_icon"])
    return sorted(slugs)


def render_shared_ts(data: dict[str, Any], slugs: list[str]) -> str:
    picker = data["picker"]
    lines = [
        "/**",
        " * GENERATED by scripts/sync_lucide_icon_catalog.py — 手編集禁止",
        " * 正本: docs/design/meta/lucide_icon_picker.json",
        " */",
        "",
        f'export const LUCIDE_ICON_FALLBACK_CATEGORY = "{data["fallbacks"]["category_tag_icon"]}" as const;',
        f'export const LUCIDE_ICON_FALLBACK_STORAGE = "{data["fallbacks"]["storage_location_icon"]}" as const;',
        "",
        "export type LucideIconSlug =",
        "  | " + "\n  | ".join(f'"{s}"' for s in slugs) + ";",
        "",
        "export const LUCIDE_ICON_SLUGS: readonly LucideIconSlug[] = [",
    ]
    for s in slugs:
        lines.append(f'  "{s}",')
    lines.append("] as const;")
    lines.append("")
    lines.append("export const LUCIDE_ICON_SLUG_SET = new Set<string>(LUCIDE_ICON_SLUGS);")
    lines.append("")
    lines.append("export type LucidePickerOption = { slug: LucideIconSlug; label_ja: string };")
    lines.append("")
    for key, const in (("category", "LUCIDE_CATEGORY_PICKER"), ("storage", "LUCIDE_STORAGE_PICKER")):
        lines.append(f"export const {const}: readonly LucidePickerOption[] = [")
        for row in picker[key]:
            label = row["label_ja"].replace('"', '\\"')
            lines.append(f'  {{ slug: "{row["slug"]}", label_ja: "{label}" }},')
        lines.append("] as const;")
        lines.append("")
    lines.append(
        "export function slugToPascal(slug: string): string {\n"
        '  return slug\n'
        '    .split("-")\n'
        '    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))\n'
        '    .join("");\n'
        "}"
    )
    lines.append("")
    return "\n".join(lines)


def render_api_py(data: dict[str, Any], slugs: list[str]) -> str:
    migration = data["bootstrap_migration"]
    cat_literal = json.dumps(data["default_category_tags"], ensure_ascii=False, indent=4)
    stor_literal = json.dumps(data["default_storage_locations"], ensure_ascii=False, indent=4)
    lines = [
        '"""Lucide アイコン slug カタログ（正本: docs/design/meta/lucide_icon_picker.json）。"""',
        "",
        "from __future__ import annotations",
        "",
        f'FALLBACK_CATEGORY = "{data["fallbacks"]["category_tag_icon"]}"',
        f'FALLBACK_STORAGE = "{data["fallbacks"]["storage_location_icon"]}"',
        "",
        "ALLOWED_SLUGS: frozenset[str] = frozenset(",
        "    {",
    ]
    for s in slugs:
        lines.append(f'        "{s}",')
    lines.append("    }")
    lines.append(")")
    lines.append("")
    lines.append("BOOTSTRAP_TO_LUCIDE: dict[str, str] = {")
    for bi, lucide in sorted(migration.items()):
        lines.append(f'    "{bi}": "{lucide}",')
    lines.extend(
        [
            "}",
            "",
            f"DEFAULT_CATEGORY_TAGS: list[dict[str, object]] = {cat_literal}",
            "",
            f"DEFAULT_STORAGE_LOCATIONS: list[dict[str, object]] = {stor_literal}",
            "",
            "",
            "def normalize_lucide_icon_slug(raw: str | None, *, fallback: str) -> str:",
            '    """bi-* レガシーと未知 slug を正規化。"""',
            "    value = (raw or \"\").strip().lower()",
            "    if not value:",
            "        return fallback",
            '    if value.startswith("bi-"):',
            "        value = BOOTSTRAP_TO_LUCIDE.get(value, fallback)",
            "    if value in ALLOWED_SLUGS:",
            "        return value",
            "    return fallback",
            "",
            "",
            "def normalize_category_icon(raw: str | None) -> str:",
            "    return normalize_lucide_icon_slug(raw, fallback=FALLBACK_CATEGORY)",
            "",
            "",
            "def normalize_storage_icon(raw: str | None) -> str:",
            "    return normalize_lucide_icon_slug(raw, fallback=FALLBACK_STORAGE)",
            "",
        ]
    )
    return "\n".join(lines)


def merge_icons_json(data: dict[str, Any], slugs: list[str]) -> None:
    icons = json.loads(ICONS_JSON.read_text(encoding="utf-8"))
    catalog = icons.get("catalog") or []
    existing: set[str] = set()
    for row in catalog:
        for name in row.get("icons") or []:
            existing.add(name)
    pascal = {slug_to_pascal(s) for s in slugs}
    merged = sorted(existing | pascal)
    filtered = [r for r in catalog if r.get("usage_ja") != "タグ・収納ピッカー"]
    filtered.append(
        {
            "usage_ja": "タグ・収納ピッカー",
            "icons": merged,
            "note_ja": "lucide_icon_picker.json から自動同期",
        }
    )
    icons["catalog"] = filtered
    ICONS_JSON.write_text(
        json.dumps(icons, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


def write_if_changed(path: Path, content: str) -> bool:
    norm = content.replace("\r\n", "\n")
    old = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.is_file() else ""
    if old == norm:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(norm, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    data = load_picker()
    slugs = collect_slugs(data)
    shared = render_shared_ts(data, slugs)
    api = render_api_py(data, slugs)

    if args.check:
        ok = True
        for path, expected in ((SHARED_TS, shared), (API_PY, api)):
            actual = path.read_text(encoding="utf-8") if path.is_file() else ""
            if actual.replace("\r\n", "\n") != expected.replace("\r\n", "\n"):
                print(f"古い: {path.relative_to(ROOT)}")
                ok = False
        return 0 if ok else 1

    changed: list[str] = []
    if write_if_changed(SHARED_TS, shared):
        changed.append(str(SHARED_TS.relative_to(ROOT)))
    if write_if_changed(API_PY, api):
        changed.append(str(API_PY.relative_to(ROOT)))
    merge_icons_json(data, slugs)
    changed.append(str(ICONS_JSON.relative_to(ROOT)))

    subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "sync_design_icons.py")], check=True
    )

    if changed:
        print("更新:", ", ".join(changed))
    else:
        print("同期済み")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
