#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""docs/design/meta/icons.json から icons.ts と icons.md 採用表を同期する。

使い方:
  python scripts/sync_design_icons.py          # 書き込み
  python scripts/sync_design_icons.py --check  # 差分があれば exit 1
  python scripts/sync_design_icons.py --check-staged  # 関連ファイルが staged なら --check
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
META = ROOT / "docs" / "design" / "meta" / "icons.json"
ICONS_TS = ROOT / "apps" / "web" / "src" / "lib" / "icons.ts"
MOBILE_ICONS_TS = ROOT / "apps" / "mobile" / "src" / "lib" / "icons.ts"
ICONS_MD = ROOT / "docs" / "design" / "icons.md"

MARKER_START = "<!-- AUTO:icons-catalog START"
MARKER_END = "<!-- AUTO:icons-catalog END -->"

ICONS_TS_HEADER = """\
/**
 * GENERATED by scripts/sync_design_icons.py — 手編集禁止
 * 正本: docs/design/meta/icons.json
 * 再生成: python scripts/sync_design_icons.py
 */
"""

MOBILE_ICONS_TS_HEADER = """\
/**
 * GENERATED by scripts/sync_design_icons.py — 手編集禁止
 * 正本: docs/design/meta/icons.json
 * パッケージ: lucide-react-native（Expo 着手時に依存追加）
 * 再生成: python scripts/sync_design_icons.py
 */
"""

STAGED_TRIGGER_PATHS = {
    "docs/design/meta/icons.json",
    "apps/web/src/lib/icons.ts",
    "apps/mobile/src/lib/icons.ts",
    "docs/design/icons.md",
}


def load_catalog() -> dict[str, Any]:
    if not META.is_file():
        raise FileNotFoundError(f"正本がありません: {META.relative_to(ROOT)}")
    data = json.loads(META.read_text(encoding="utf-8"))
    if not isinstance(data.get("catalog"), list):
        raise ValueError("icons.json: catalog は配列必須")
    return data


def collect_icon_names(catalog: list[dict[str, Any]]) -> list[str]:
    names: set[str] = set()
    for row in catalog:
        icons = row.get("icons") or []
        if not isinstance(icons, list) or not icons:
            raise ValueError(f"catalog 行に icons がありません: {row!r}")
        for name in icons:
            if not isinstance(name, str) or not name.isidentifier():
                raise ValueError(f"不正な lucide 名: {name!r}")
            names.add(name)
    return sorted(names)


def render_icons_ts(data: dict[str, Any], *, package: str, header: str) -> str:
    names = collect_icon_names(data["catalog"])
    lines = [header.rstrip(), "export {"]
    for name in names:
        lines.append(f"  {name},")
    lines.append("} from \"" + package + "\";")
    lines.append("")
    if package == "lucide-react":
        export_types = data.get("export_types") or ["LucideIcon", "LucideProps"]
        if not isinstance(export_types, list):
            raise ValueError("export_types は配列必須")
        type_list = ", ".join(str(t) for t in export_types)
        lines.append("export type { " + type_list + ' } from "' + package + '";')
        lines.append("")
    return "\n".join(lines)


def format_icon_names(icons: list[str]) -> str:
    return " / ".join(f"`{name}`" for name in icons)


def render_catalog_table(catalog: list[dict[str, Any]]) -> str:
    rows = [
        "| 用途 | lucide 名 | メモ |",
        "|------|-----------|------|",
    ]
    for row in catalog:
        usage = str(row.get("usage_ja", "")).replace("|", "\\|")
        note = str(row.get("note_ja", "")).replace("|", "\\|")
        icons = row.get("icons") or []
        rows.append(f"| {usage} | {format_icon_names(icons)} | {note} |")
    return "\n".join(rows)


def render_catalog_block(catalog: list[dict[str, Any]]) -> str:
    table = render_catalog_table(catalog)
    return (
        f"{MARKER_START} — sync_design_icons.py。手編集禁止 -->\n"
        f"{table}\n"
        f"{MARKER_END}"
    )


def patch_icons_md(content: str, catalog: list[dict[str, Any]]) -> str:
    block = render_catalog_block(catalog)
    pattern = re.compile(
        rf"{re.escape(MARKER_START)}.*?{re.escape(MARKER_END)}",
        re.DOTALL,
    )
    if not pattern.search(content):
        raise ValueError(
            f"{ICONS_MD.relative_to(ROOT)} に AUTO マーカーがありません。"
            " docs/design/icons.md を確認してください。"
        )
    return pattern.sub(block, content, count=1)


def staged_trigger_files() -> set[str]:
    try:
        out = subprocess.run(
            ["git", "diff", "--cached", "--name-only", "--diff-filter=ACMR"],
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return set()
    paths = {line.strip().replace("\\", "/") for line in out.stdout.splitlines() if line.strip()}
    return paths & STAGED_TRIGGER_PATHS


def write_if_changed(path: Path, content: str) -> bool:
    normalized = content.replace("\r\n", "\n")
    existing = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.is_file() else ""
    if existing == normalized:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(normalized, encoding="utf-8", newline="\n")
    return True


def expected_outputs(data: dict[str, Any]) -> dict[Path, str]:
    web_ts = render_icons_ts(data, package="lucide-react", header=ICONS_TS_HEADER)
    mobile_ts = render_icons_ts(
        data, package="lucide-react-native", header=MOBILE_ICONS_TS_HEADER
    )
    icons_md = patch_icons_md(ICONS_MD.read_text(encoding="utf-8"), data["catalog"])
    return {
        ICONS_TS: web_ts,
        MOBILE_ICONS_TS: mobile_ts,
        ICONS_MD: icons_md,
    }


def check_outputs(data: dict[str, Any]) -> list[str]:
    stale: list[str] = []
    for path, expected in expected_outputs(data).items():
        if not path.is_file():
            stale.append(str(path.relative_to(ROOT)))
            continue
        actual = path.read_text(encoding="utf-8").replace("\r\n", "\n")
        if actual != expected.replace("\r\n", "\n"):
            stale.append(str(path.relative_to(ROOT)))
    return stale


def sync(write: bool) -> int:
    data = load_catalog()
    outputs = expected_outputs(data)
    if write:
        changed: list[str] = []
        for path, content in outputs.items():
            if write_if_changed(path, content):
                changed.append(str(path.relative_to(ROOT)))
        if changed:
            print("更新:", ", ".join(changed))
        else:
            print("同期済み（変更なし）")
        return 0

    stale = check_outputs(data)
    if stale:
        print("古い生成物:", ", ".join(stale))
        print("実行: python scripts/sync_design_icons.py")
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="design icons 同期")
    parser.add_argument(
        "--check",
        action="store_true",
        help="生成物が正本と一致するか検査（不一致なら exit 1）",
    )
    parser.add_argument(
        "--check-staged",
        action="store_true",
        help="icons 関連が staged のときだけ --check",
    )
    args = parser.parse_args()

    if args.check_staged:
        if not staged_trigger_files():
            return 0
        return sync(write=False)

    if args.check:
        return sync(write=False)

    return sync(write=True)


if __name__ == "__main__":
    raise SystemExit(main())
