-- 更新: 手 — 人が直すテンプレ。凡例: docs/README.md
-- 新規テーブル用テンプレート（oshi_app）
-- 使い方: 表名・列を置き換え、migration に載せて適用する。
-- 詳細: docs/db/security.md / docs/db/naming.md / skill db-schema-change

-- ========== 例A: ユーザー所有（members_id）→ 連携時に wired ==========
/*
create table public.example_item (
  example_item_id bigint generated by default as identity primary key,
  members_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.example_item enable row level security;

-- 既定で anon/authenticated に自動 GRANT しない前提。連携するまで権限を付けない。
-- 連携開始時のみ:
-- grant select, insert, update, delete on public.example_item to authenticated;
-- grant all on public.example_item to service_role;

create policy example_item_self_all
  on public.example_item
  for all
  to authenticated
  using ( (select auth.uid()) = members_id )
  with check ( (select auth.uid()) = members_id );

create index example_item_members_id_idx on public.example_item (members_id);
*/

-- ========== 例B: 共有マスタ（精査前は権限なし）==========
/*
create table public.example_master (
  example_master_id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

alter table public.example_master enable row level security;

-- 精査・連携まで GRANT しない（service_role のみ管理用に付与可）
-- grant all on public.example_master to service_role;

-- 読み取り専用で連携するとき例:
-- grant select on public.example_master to authenticated;
-- create policy example_master_read
--   on public.example_master for select to authenticated
--   using ( true );
*/

-- 禁止: using (true) の write ポリシーを authenticated/anon に付ける
-- 禁止: anon にユーザーデータを GRANT する
-- 禁止: フロントに service_role を置く
