-- 製品の外部マーケット参照（楽天・任意URL。将来 Amazon）

create table public.product_external_ref (
  product_external_ref_id bigint generated by default as identity primary key,
  members_id uuid not null references auth.users (id) on delete cascade,
  registered_product_id integer not null
    references public.registered_product (registered_product_id) on delete cascade,
  source text not null,
  external_item_code text null,
  product_url text not null,
  shop_name text null,
  label text null,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_external_ref_source_check
    check (source = any (array['rakuten'::text, 'amazon'::text, 'manual'::text])),
  constraint product_external_ref_product_source_uidx
    unique (registered_product_id, source),
  constraint product_external_ref_rakuten_required check (
    source <> 'rakuten'
    or (
      external_item_code is not null
      and length(btrim(external_item_code)) > 0
      and shop_name is not null
      and length(btrim(shop_name)) > 0
      and length(btrim(product_url)) > 0
    )
  ),
  constraint product_external_ref_manual_url check (
    source <> 'manual'
    or length(btrim(product_url)) > 0
  )
);

comment on table public.product_external_ref is
  '登録製品の外部商品参照（楽天必須セット・任意URL・将来Amazon）';
comment on column public.product_external_ref.source is
  'rakuten / amazon / manual';
comment on column public.product_external_ref.external_item_code is
  '楽天 itemCode 等。rakuten では必須';
comment on column public.product_external_ref.product_url is
  '再購入用URL（楽天はアフィ優先）';
comment on column public.product_external_ref.shop_name is
  '出品店名。rakuten では必須';
comment on column public.product_external_ref.label is
  '任意表示名（メルカリ等）';
comment on column public.product_external_ref.is_primary is
  '主リンク（再購入ボタン用）';

alter table public.product_external_ref enable row level security;

create policy product_external_ref_self_all
  on public.product_external_ref
  for all
  to authenticated
  using ( (select auth.uid()) = members_id )
  with check ( (select auth.uid()) = members_id );

create policy product_external_ref_reject_anonymous
  on public.product_external_ref
  as restrictive
  for all
  to authenticated
  using ( public.jwt_is_permanent_user() )
  with check ( public.jwt_is_permanent_user() );

create index product_external_ref_members_id_idx
  on public.product_external_ref (members_id);

create index product_external_ref_product_id_idx
  on public.product_external_ref (registered_product_id);

grant select, insert, update, delete on table public.product_external_ref to authenticated;
grant all on table public.product_external_ref to service_role;
revoke all on table public.product_external_ref from anon;

grant usage, select on sequence public.product_external_ref_product_external_ref_id_seq
  to authenticated;
grant all on sequence public.product_external_ref_product_external_ref_id_seq
  to service_role;
