-- ギャラリー保存済みビュー（名前付きフィルタ＋並び）。無料・上限は API で 20。

create table public.gallery_view (
  gallery_view_id bigint generated by default as identity primary key,
  members_id uuid not null references auth.users (id) on delete cascade,
  view_name text not null,
  q text null,
  category_tag_ids integer[] not null default '{}'::integer[],
  storage_location_ids integer[] not null default '{}'::integer[],
  color_tag_slots integer[] not null default '{}'::integer[],
  list_sort text not null default 'newest',
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint gallery_view_view_name_len_check
    check (char_length(view_name) >= 1 and char_length(view_name) <= 40),
  constraint gallery_view_list_sort_check
    check (list_sort = any (array['newest'::text, 'name'::text, 'created_at'::text])),
  constraint gallery_view_color_tag_slots_check
    check (color_tag_slots <@ array[1, 2, 3, 4, 5, 6, 7]::integer[]),
  constraint gallery_view_members_view_name_key
    unique (members_id, view_name)
);

comment on table public.gallery_view is
  'ユーザー別のギャラリー保存ビュー（フィルタ＋並び。JSON 黒箱なし）';
comment on column public.gallery_view.view_name is
  '表示名（1〜40文字。メンバー内で一意）';
comment on column public.gallery_view.q is
  '検索語。空は null';
comment on column public.gallery_view.category_tag_ids is
  'カテゴリ ID 配列（同種 OR）';
comment on column public.gallery_view.storage_location_ids is
  '収納 ID 配列（同種 OR）';
comment on column public.gallery_view.color_tag_slots is
  '色スロット 1..7 の配列（同種 OR）';
comment on column public.gallery_view.list_sort is
  '並び: newest / name / created_at';
comment on column public.gallery_view.display_order is
  '表示順（小さいほど先。第1版は作成時 0）';

alter table public.gallery_view enable row level security;

create policy gallery_view_self_all
  on public.gallery_view
  for all
  to authenticated
  using ( (select auth.uid()) = members_id )
  with check ( (select auth.uid()) = members_id );

create index gallery_view_members_id_idx
  on public.gallery_view (members_id);

grant select, insert, update, delete on table public.gallery_view to authenticated;
grant all on table public.gallery_view to service_role;
revoke all on table public.gallery_view from anon;
