/**
 * GENERATED by scripts/sync_design_icons.py — 手編集禁止
 * 正本: docs/design/meta/icons.json
 * 再生成: python scripts/sync_design_icons.py
 */
export {
  AlertCircle,
  Check,
  ChevronLeft,
  Image,
  Images,
  Loader2,
  MapPin,
  Plus,
  ScanBarcode,
  Search,
  Settings,
  Tag,
  Trash2,
  X,
} from "lucide-react";

export type { LucideIcon, LucideProps } from "lucide-react";
